#!/bin/bash

set -x
#docker run --detach \
docker container rm qlmux_proxy --force --volumes 
docker run \
	--name qlmux_proxy \
	--net=host \
	--hostname qllabels.local \
	--publish 9100-9104:9100-9104 \
	--publish 5000:5000 \
	--publish 161:161/udp \
	--restart always \
	--env PYTHONUNBUFFERED=1 \
	-ti qlmux_proxy \
	/bin/bash
	#qlmux_proxy
	#--network qlmux_proxy \

