#!/bin/bash

set -x
docker container stop qlmux_proxy
docker image rm --force qlmux_proxy
docker build --tag qlmux_proxy .
exit 0
docker container rm qlmux_proxy --force --volumes 
docker run \
	--detach \
	--name qlmux_proxy \
	--net=host \
	--restart always \
	--env PYTHONUNBUFFERED=1 \
	-v /etc/localtime:/etc/localtime:ro \
	-t qlmux_proxy 

